export const DEFAULT_ACRONYM = 'MK'

export const DEFAULT_SEARCH_SIZE = 10

export const ALLOWED_METHODS = ['POST', 'GET']

export const MASTERDATA_ACCOUNTNAME = "lojavtex"

export const API_CREDENTIALS = {
    appKey: 'vtexappkey-lojavtex-IZOGBG',
    appToken: 'ZPABJUQEEYZBNMMPRZUNVEQQGMGTIZVCOZWXAMHSOPNJMCGDTFRROKAVZKUXNXVFDXMNQPPFSCZGRGDEGCZCIENEYBXQSKEQUIGPPTNDQMZMKUDSGPQLYSWYJIOORYNH'
}